# All these are used inside Vagrantfile
name: "rainbox"

box_name: "precise64"
box_url: "http://files.vagrantup.com/precise64.box"

memory: 512 # megabytes for VM
guest_ip: "192.168.2.60"

ports:
  - {guest: 3000, host: 3000}

timezone: "Europe/Ljubljana"
