# Default config for Vagrant
# use vagrantconfig_local.yml to override these settings and put it to .gitignore

project_name: rainbox
box_name: precise64
box_url: http://files.vagrantup.com/precise64.box
memory: 512
guest_ip: 192.168.1.10

ports:
  - {guest: 3000, host: 3000}

chef_conf:
  databases:
    - postgres

  packages:
    - vim

  languages:
    golang:
      version: ~ # not yet supported, currently 1.1.2
    ruby:
      version: 2.1.0-preview2
